import React from "react";
import { Box } from "@hypobox/react";
import Head from "next/head";
import Link from "next/link";

import { Header, headerGap } from "../../components/Header";
import { Footer } from "../../components/Footer";
import { Gutter, gutter } from "../../components/Gutter";
import { Pill } from "../../components/Pill";
import { ArrowLeft } from "../../components/icons/ArrowLeft";

export function Social(props: { title: string; value: string; href: string }) {
  return (
    <Box mb={[2, 4, 6]}>
      <Box as="h4" fs={6} fw={9} caps mb={1} c="lightBlue">
        {props.title}
      </Box>
      <Box
        as={Link}
        href={props.href}
        fs={5}
        c="blue"
        dib
        title={props.title}
        w={1}
        cx={{
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
        }}
      >
        {props.value}
      </Box>
    </Box>
  );
}

export function Image(props: { src: string }) {
  return (
    <Box rel w={[1, 1, 1 / 2]}>
      <Box rel pb="66%">
        <Box
          as="img"
          src={props.src}
          w={1}
          h={1}
          abs
          cover
          m="auto"
          cx={{ objectFit: "cover" }}
        />
      </Box>
    </Box>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Side By Side | Luminous Directory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box bg="white">
        <Header />

        <Gutter pt={headerGap}>
          <Box f aic pt={10} pb={[5, 5, 8]}>
            <Pill>#205</Pill>

            <Box as={Link} href="/" f aic pl={[4, 4, 6]}>
              <ArrowLeft w={16} />
              <Box as="span" fs={6} pl={1}>
                Return to all listings
              </Box>
            </Box>
          </Box>

          <Box as="h1" fs={0} fw={9} pb={[5, 5, 8]}>
            Derek Christiansen Art
          </Box>

          <Box f fw mx={-12}>
            <Box px={4} pb={[5, 5, 0]} w={[1, 1, 1 / 4]}>
              <Social
                title="Website"
                value="derekchristiansenart.com"
                href="https://derekchristiansenart.com"
              />
              <Social
                title="Email"
                value="hi@derekchristiansenart.com"
                href="mailto:hi@derekchristiansenart.com"
              />
              <Social
                title="Instagram"
                value="@derekchristiansenart"
                href="https://derekchristiansenart.com"
              />
            </Box>

            <Box px={4} w={[1, 1, 3 / 4, 1 / 2]} className="content">
              <Box as="p">
                Side By Side is a shared-workspace-meets-clubhouse with members
                spanning a variety of creative and technical fields. Current
                residents include Eric, a software engineer, Melanie, a graphic
                designer and art director, Lee, a senior consultant and
                projector manger, and Jon, a social media director and
                photographer.
              </Box>

              <Box as="p">
                Learn more about us and inquire about current desk availability
                at our website.
              </Box>

              <Box as="p">
                Side By Side is a shared-workspace-meets-clubhouse with members
                spanning a variety of creative and technical fields. Current
                residents include Eric, a software engineer, Melanie, a graphic
                designer and art director, Lee, a senior consultant and
                projector manger, and Jon, a social media director and
                photographer.
              </Box>

              <Box as="p">
                Learn more about us and inquire about current desk availability
                at our website.
              </Box>
            </Box>
          </Box>

          <Box pt={[5, 5, 8]} f fw>
            <Image src="https://front-of-house.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd89d8e0f-52a9-472d-8071-bcd4c612073c%2FSideBySide-1.jpg?id=f39bf1db-e1a9-4625-84e5-26ec7744fcd7&table=block&spaceId=001dba87-1c49-4da0-a335-d5df47eaf6ed&width=2000&userId=&cache=v2" />
            <Image src="https://front-of-house.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd89d8e0f-52a9-472d-8071-bcd4c612073c%2FSideBySide-1.jpg?id=f39bf1db-e1a9-4625-84e5-26ec7744fcd7&table=block&spaceId=001dba87-1c49-4da0-a335-d5df47eaf6ed&width=2000&userId=&cache=v2" />
            <Image src="https://front-of-house.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd89d8e0f-52a9-472d-8071-bcd4c612073c%2FSideBySide-1.jpg?id=f39bf1db-e1a9-4625-84e5-26ec7744fcd7&table=block&spaceId=001dba87-1c49-4da0-a335-d5df47eaf6ed&width=2000&userId=&cache=v2" />
            <Image src="https://front-of-house.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd89d8e0f-52a9-472d-8071-bcd4c612073c%2FSideBySide-1.jpg?id=f39bf1db-e1a9-4625-84e5-26ec7744fcd7&table=block&spaceId=001dba87-1c49-4da0-a335-d5df47eaf6ed&width=2000&userId=&cache=v2" />
          </Box>
        </Gutter>

        <Footer />
      </Box>
    </>
  );
}
